[package]
name = "bls_sigs_test"
version = "0.3.0"
authors = ["kwantam <kwantam@gmail.com>"]
license = "MIT"

[dependencies]
bls_sigs_ref = { path = "../" }
#pairing-plus = { path = "../../../pairing-plus" }
pairing-plus = "0.19"
sha2 = "0.8"
